OrdererOrgs:
  - Name: OrdererOrg
    Domain: idsnet.local
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: NodeAlphaOrg
    Domain: node-alpha.idsnet.local
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: NodeBetaOrg
    Domain: node-beta.idsnet.local
    Template:
      Count: 1
    Users:
      Count: 1
